version : '3'
services:
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - "./schemas/create_db.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./schemas/create_tables.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./schemas/inserts.sql:/docker-entrypoint-initdb.d/3.sql"